project_id = "kcwibsbtquhbqngjcdbe"

[functions.safety-analysis]
verify_jwt = false

[functions.get-maps-key]
verify_jwt = false

[functions.notify-volunteers]
verify_jwt = false

[functions.send-emergency-email]
verify_jwt = false
